apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 969333511575.dkr.ecr.ap-south-1.amazonaws.com/node-app:4b861109
        ports:
        - containerPort: 3000
